path = "/gpfs/projects/FrenkelGroup/kaif/FDMNES_cal/Pt_shape_proj_7/particle_test" 
exe_path='/gpfs/home/kaifzheng/software/parallel_fdmnes'
scratch_path="/gpfs/scratch/kaifzheng/fdmnes/calculation"
template_dir='template.inp'
Absorber = "Pt"
cleanup= true
restart= false
